version: '3.7'

services:
  smart-brain-api: 
    container_name: backend
    # image: node:carbon-jessie
    build: ./
    command: npm run start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    volumes:
      - ./://usr/src/smart-brain-api
